-- MASTER SCHEMA FOR CLEO AI --
-- Copy and paste this to the SQL Editor in Supabase to ensure everything is correct --

-- 1. Inventory Table
CREATE TABLE IF NOT EXISTS public.inventory (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "Material" TEXT,
    "Subproducto" TEXT,
    "CantDisponible" FLOAT,
    "Precio Contado" FLOAT,
    "categoria" TEXT,
    "marca" TEXT,
    "modelo_limpio" TEXT,
    "especificaciones" TEXT,
    "tip_venta" TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Metadata Table
CREATE TABLE IF NOT EXISTS public.metadata (
    id INT PRIMARY KEY,
    last_update TEXT,
    status TEXT
);

-- 3. Quotas Mapping
CREATE TABLE IF NOT EXISTS public.quotas (
    id INT PRIMARY KEY,
    data JSONB,
    updated_at TEXT
);

-- 4. Specs/Images Mapping
CREATE TABLE IF NOT EXISTS public.specs_mapping (
    id INT PRIMARY KEY,
    data JSONB,
    updated_at TEXT
);

-- 5. Expert Knowledge
CREATE TABLE IF NOT EXISTS public.expert_knowledge (
    id INT PRIMARY KEY,
    data JSONB,
    updated_at TEXT
);

-- Disable RLS for easier backend access
ALTER TABLE public.inventory DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.metadata DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.quotas DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.specs_mapping DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.expert_knowledge DISABLE ROW LEVEL SECURITY;

-- Migration helper: If columns are missing, run these individually:
-- ALTER TABLE public.inventory ADD COLUMN IF NOT EXISTS "CantDisponible" FLOAT;
-- ALTER TABLE public.inventory ADD COLUMN IF NOT EXISTS "Precio Contado" FLOAT;
-- ALTER TABLE public.inventory ADD COLUMN IF NOT EXISTS "tip_venta" TEXT;
