-- COPIA Y PEGA ESTO EN EL "SQL EDITOR" DE SUPABASE (Está en la barra lateral izquierda) --

-- 1. Tabla de Inventario (Memoria de productos)
CREATE TABLE IF NOT EXISTS public.inventory (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "Material" TEXT,
    "Subproducto" TEXT,
    "Precio" TEXT,
    "categoria" TEXT,
    "marca" TEXT,
    "modelo_limpio" TEXT,
    "especificaciones" TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Tabla de Metadatos (Fecha de actualización)
CREATE TABLE IF NOT EXISTS public.metadata (
    id INT PRIMARY KEY,
    last_update TEXT,
    status TEXT
);

-- 3. Desactivar RLS (Para que el backend pueda escribir sin problemas inicialmente)
ALTER TABLE public.inventory DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.metadata DISABLE ROW LEVEL SECURITY;
